# Generated by Django 5.0 on 2024-06-28 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('fee', models.IntegerField(default=0)),
                ('minMember', models.IntegerField(default=1)),
                ('maxMember', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('extra_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionType', models.CharField(default='', max_length=255, null=True)),
                ('instiName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.TextField()),
                ('email', models.EmailField(default=True, max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=25)),
                ('instituteID', models.CharField(max_length=255, null=True)),
                ('gradYear', models.IntegerField(default=6969)),
                ('stream', models.TextField(null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CACode', models.CharField(max_length=8)),
                ('registration', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('user_id', models.TextField(default='')),
                ('participants', models.TextField()),
                ('transaction_id', models.TextField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField()),
                ('CACode', models.CharField(max_length=10, null=True)),
                ('event_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
